sudo: false

language: cpp

compiler:
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test

addons:
    apt:
        packages:
            - g++-4.8

before_script:
    - export CXX="g++-4.8"

script:
    - $CXX -std=c++11 TwoSum/TwoSum.cpp -o TwoSum/TwoSum

branches:
    only:
        - master
