language: cpp

compiler:
    - gcc

env:
    matrix:
        - PLATFORM = linux DEBUG=1

before_install:
    - echo $LANG

script:
    - $CXX -std=c++11 TwoSum/TwoSum.cpp -o TwoSum

branches:
    only:
        - master
