sudo: false
language: cpp

compiler:
    - gcc

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5

script:
    - $CXX -std=c++11 TwoSum/TwoSum.cpp -o TwoSum/TwoSum
    - $CXX -std=c++11 AddTwoNumbers/AddTwoNumbers.cpp -o AddTwoNumbers/AddTwoNumbers

branches:
    only:
        - master
