sudo: false
language: cpp

compiler:
    - gcc

install:
    - if [ "$CXX" = "g++" ] then export CXX="g++-4.8"; fi

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8

script:
    - $CXX -std=c++11 TwoSum/TwoSum.cpp -o TwoSum/TwoSum

branches:
    only:
        - master
